apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
 name: apache
 namespace: argocd
spec:
 project: default
 source:
   repoURL: https://github.com/LondheShubham153/argocd-demos.git
   targetRevision: main
   path: cli_approach/apache
 destination:
   server: https://192.168.49.2:8443
   namespace: default
 syncPolicy:
   automated:
     prune: true
     selfHeal: true
   syncOptions:
     - CreateNamespace=true
